export const styles = {
  container: {
    textAlign: "center",
    fontFamily: "Arial",
    padding: "20px",
  },
  authGlassCard: {
    background: "rgba(255,255,255,0.75)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(255,255,255,0.6)",
    borderRadius: "28px",
    boxShadow: "0 30px 80px rgba(76, 29, 149, 0.12)",
    padding: "44px 40px 40px",
    maxWidth: "420px",
    width: "100%",
    textAlign: "center",
  },
  authBrandLogo: {
    fontWeight: "800",
    fontSize: "20px",
    color: "#7c3aed",
    marginBottom: "24px",
  },
  authTitleLg: {
    fontSize: "26px",
    fontWeight: "800",
    color: "#111827",
    margin: "0 0 6px",
  },
  authSubtitleLg: {
    fontSize: "14px",
    color: "#6b7280",
    marginBottom: "28px",
  },
  authInput: {
    width: "100%",
    padding: "14px 16px",
    borderRadius: "14px",
    border: "1px solid rgba(17,24,39,0.1)",
    background: "rgba(255,255,255,0.8)",
    fontSize: "14px",
    marginBottom: "14px",
    boxSizing: "border-box",
    outline: "none",
  },
  authPrimaryBtn: {
    width: "100%",
    padding: "14px",
    background: "linear-gradient(135deg, #7c3aed, #6d28d9)",
    color: "white",
    border: "none",
    borderRadius: "14px",
    cursor: "pointer",
    fontWeight: "700",
    fontSize: "15px",
    boxShadow: "0 14px 30px rgba(124, 58, 237, 0.3)",
    marginTop: "4px",
  },
  authSwitchText: {
    marginTop: "18px",
    color: "#7c3aed",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
  },
  authLinkSmall: {
    color: "#7c3aed",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    textAlign: "right",
    marginTop: "-6px",
    marginBottom: "8px",
  },
  authDivider: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    color: "#9ca3af",
    fontSize: "12px",
    margin: "18px 0",
  },
  authDividerLine: {
    flex: 1,
    height: "1px",
    background: "rgba(17,24,39,0.1)",
  },
  authErrorBox: {
    background: "#fee2e2",
    color: "#b91c1c",
    padding: "10px 14px",
    borderRadius: "12px",
    fontSize: "13px",
    marginBottom: "16px",
    textAlign: "left",
  },
  authInfoBox: {
    background: "#dcfce7",
    color: "#15803d",
    padding: "10px 14px",
    borderRadius: "12px",
    fontSize: "13px",
    marginBottom: "16px",
    textAlign: "left",
  },
  authCodeInput: {
    width: "100%",
    padding: "16px",
    borderRadius: "14px",
    border: "1px solid rgba(17,24,39,0.1)",
    background: "rgba(255,255,255,0.8)",
    fontSize: "22px",
    letterSpacing: "8px",
    textAlign: "center",
    fontWeight: "700",
    marginBottom: "18px",
    boxSizing: "border-box",
    outline: "none",
  },
  gamesBackBtn: {
    position: "absolute",
    top: "32px",
    left: "44px",
    padding: "10px 20px",
    border: "none",
    borderRadius: "999px",
    background: "rgba(17,24,39,0.06)",
    color: "#111827",
    fontWeight: "600",
    fontSize: "13px",
    cursor: "pointer",
  },
  badgeBlue: {
    background: "linear-gradient(135deg, #3b82f6, #2563eb)",
    boxShadow: "0 10px 20px rgba(37,99,235,0.3)",
  },
  badgeTeal: {
    background: "linear-gradient(135deg, #14b8a6, #0d9488)",
    boxShadow: "0 10px 20px rgba(13,148,136,0.3)",
  },
  badgeRed: {
    background: "linear-gradient(135deg, #ef4444, #dc2626)",
    boxShadow: "0 10px 20px rgba(220,38,38,0.3)",
  },
  leaderboardList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginTop: "8px",
    textAlign: "left",
  },
  leaderboardRow: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    background: "#ffffff",
    borderRadius: "18px",
    padding: "16px 20px",
    boxShadow: "0 8px 20px rgba(17,24,39,0.06)",
    border: "1px solid rgba(17,24,39,0.04)",
  },
  rankBadge: {
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    fontSize: "15px",
    color: "white",
    flexShrink: 0,
  },
  rankGold: {
    background: "linear-gradient(135deg, #fbbf24, #d97706)",
    boxShadow: "0 10px 20px rgba(217,119,6,0.35)",
  },
  rankSilver: {
    background: "linear-gradient(135deg, #cbd5e1, #94a3b8)",
    boxShadow: "0 10px 20px rgba(148,163,184,0.3)",
  },
  rankBronze: {
    background: "linear-gradient(135deg, #d69154, #b45309)",
    boxShadow: "0 10px 20px rgba(180,83,9,0.3)",
  },
  rankDefault: {
    background: "#e5e7eb",
    color: "#374151",
    boxShadow: "none",
  },
  leaderboardEmailCol: {
    flex: 1,
    fontWeight: "700",
    fontSize: "15px",
    color: "#111827",
  },
  leaderboardXpCol: {
    fontWeight: "700",
    fontSize: "14px",
    color: "#7c3aed",
    whiteSpace: "nowrap",
  },
  leaderboardEmptyText: {
    color: "#6b7280",
    fontSize: "14px",
    textAlign: "center",
    marginTop: "24px",
  },
  xpBadgeTop: {
    position: "absolute",
    top: "32px",
    right: "44px",
    background: "linear-gradient(135deg, #7c3aed, #6d28d9)",
    borderRadius: "999px",
    padding: "8px 20px",
    fontWeight: "700",
    color: "#ffffff",
    fontSize: "14px",
    boxShadow: "0 10px 24px rgba(124, 58, 237, 0.3)",
  },
  // ---- New Dashboard redesign tokens ----
  appShell: {
    minHeight: "100vh",
    width: "100%",
    background:
      "radial-gradient(circle at top right, rgba(167,139,250,0.28), transparent 45%), radial-gradient(circle at bottom left, rgba(74,222,128,0.25), transparent 45%), #f7f7fb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    boxSizing: "border-box",
    fontFamily: "'Segoe UI', sans-serif",
  },
  glassCard: {
    background: "rgba(255,255,255,0.75)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(255,255,255,0.6)",
    borderRadius: "32px",
    boxShadow: "0 30px 80px rgba(76, 29, 149, 0.12)",
    padding: "56px 64px 72px",
    maxWidth: "1100px",
    width: "100%",
    textAlign: "center",
    position: "relative",
  },
  brandLogo: {
    position: "absolute",
    top: "32px",
    left: "44px",
    fontWeight: "800",
    fontSize: "20px",
    color: "#7c3aed",
  },
  dashboardIconBadge: {
    width: "72px",
    height: "72px",
    borderRadius: "20px",
    background: "linear-gradient(135deg, #ede9fe, #ddd6fe)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 20px",
    fontSize: "34px",
    boxShadow: "0 10px 24px rgba(124,58,237,0.15)",
  },
  dashboardTitleLg: {
    fontSize: "44px",
    fontWeight: "800",
    color: "#111827",
    margin: "0 0 10px",
  },
  dashboardSubtitle: {
    fontSize: "16px",
    color: "#6b7280",
    marginBottom: "48px",
  },
  dashCardGrid: {
    display: "flex",
    justifyContent: "center",
    gap: "28px",
    flexWrap: "wrap",
  },
  dashCard: {
    width: "260px",
    minHeight: "190px",
    background: "#ffffff",
    borderRadius: "24px",
    padding: "32px 26px",
    boxShadow: "0 8px 20px rgba(17,24,39,0.12), 0 2px 6px rgba(17,24,39,0.06)",
    border: "1px solid rgba(17,24,39,0.06)",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "14px",
  },
  cardIconBadge: {
    width: "60px",
    height: "60px",
    borderRadius: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "28px",
    color: "white",
    marginBottom: "4px",
  },
  dashCardTitle: {
    fontSize: "19px",
    fontWeight: "700",
    color: "#111827",
  },
  dashCardSubtitle: {
    fontSize: "13px",
    color: "#9ca3af",
  },
  pillLogoutBtn: {
    marginTop: "44px",
    padding: "14px 36px",
    border: "none",
    borderRadius: "999px",
    background: "linear-gradient(135deg, #ef4444, #dc2626)",
    color: "white",
    fontWeight: "700",
    fontSize: "15px",
    cursor: "pointer",
    boxShadow: "0 14px 30px rgba(220,38,38,0.3)",
  },
  subtitleHighlight: {
    color: "#7c3aed",
    fontWeight: "700",
  },
  badgePurple: {
    background: "linear-gradient(135deg, #8b5cf6, #7c3aed)",
    boxShadow: "0 10px 20px rgba(124,58,237,0.3)",
  },
  badgeGreen: {
    background: "linear-gradient(135deg, #22c55e, #16a34a)",
    boxShadow: "0 10px 20px rgba(22,163,74,0.3)",
  },
  badgeAmber: {
    background: "linear-gradient(135deg, #d97706, #b45309)",
    boxShadow: "0 10px 20px rgba(180,83,9,0.3)",
  },
 guideRow: {
    display: "flex",
    justifyContent: "center",
    gap: "16px",
    marginTop: "8px",
    flexWrap: "wrap",
  },
  guideOption: {
    width: "180px",
    padding: "20px 16px",
    background: "#ffffff",
    borderRadius: "18px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "700",
    textAlign: "center",
    color: "#111827",
    border: "2px solid transparent",
    boxShadow: "0 8px 20px rgba(17,24,39,0.06)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "10px",
  },
  guideOptionActive: {
    border: "2px solid #7c3aed",
    boxShadow: "0 14px 30px rgba(124,58,237,0.2)",
    color: "#7c3aed",
  },
  guideIconCircle: {
    width: "44px",
    height: "44px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #ede9fe, #ddd6fe)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "20px",
  },
  guideDescBox: {
    maxWidth: "640px",
    margin: "32px auto 0",
    padding: "24px 28px",
    background: "#f9f9fb",
    border: "1px solid rgba(17,24,39,0.06)",
    borderRadius: "18px",
    fontSize: "14px",
    lineHeight: "1.7",
    color: "#374151",
    textAlign: "left",
  },
  quizHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "24px",
    flexWrap: "wrap",
    gap: "12px",
  },
  quizLevelBadge: {
    background: "linear-gradient(135deg, #ede9fe, #ddd6fe)",
    color: "#7c3aed",
    fontWeight: "700",
    fontSize: "13px",
    padding: "8px 18px",
    borderRadius: "999px",
  },
  quizScoreBadge: {
    background: "linear-gradient(135deg, #dcfce7, #bbf7d0)",
    color: "#15803d",
    fontWeight: "700",
    fontSize: "13px",
    padding: "8px 18px",
    borderRadius: "999px",
  },
  timerCircle: {
    width: "52px",
    height: "52px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    fontSize: "18px",
    color: "white",
    background: "linear-gradient(135deg, #7c3aed, #6d28d9)",
    boxShadow: "0 10px 24px rgba(124,58,237,0.3)",
  },
  timerCircleWarn: {
    background: "linear-gradient(135deg, #ef4444, #dc2626)",
    boxShadow: "0 10px 24px rgba(220,38,38,0.35)",
  },
  quizFlagCard: {
    background: "#ffffff",
    borderRadius: "24px",
    padding: "28px",
    boxShadow: "0 20px 50px rgba(17,24,39,0.08)",
    border: "1px solid rgba(17,24,39,0.05)",
    textAlign: "center",
  },
  quizFlagImg: {
    width: "220px",
    height: "132px",
    objectFit: "cover",
    borderRadius: "14px",
    marginBottom: "24px",
    border: "1px solid #eee",
    boxShadow: "0 10px 24px rgba(0,0,0,0.1)",
  },
  quizOptions: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  quizOptionBtn: {
    padding: "14px",
    borderRadius: "14px",
    border: "1px solid rgba(17,24,39,0.08)",
    cursor: "pointer",
    background: "#f9fafb",
    fontSize: "15px",
    fontWeight: "600",
    color: "#111827",
  },
  quizProgressText: {
    textAlign: "center",
    marginTop: "18px",
    color: "#6b7280",
    fontSize: "13px",
    fontWeight: "600",
  },
  quizLoadingText: {
    textAlign: "center",
    fontSize: "18px",
    fontWeight: "700",
    color: "#7c3aed",
  },
  quizFinishedEmoji: {
    fontSize: "48px",
    marginBottom: "8px",
  },
  quizFinishedScore: {
    fontSize: "32px",
    fontWeight: "800",
    color: "#111827",
    margin: "8px 0 28px",
  },
  center: {
    textAlign: "center",
    marginTop: "100px",
  },
  levelsListWrap: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    marginTop: "8px",
    alignItems: "center",
  },
  levelRow: {
  width: "100%",
  maxWidth: "420px",
  display: "flex",
  alignItems: "center",
  gap: "16px",
  background: "linear-gradient(135deg, #ede9fe, #f8fafc)",
  borderRadius: "18px",
  padding: "18px 22px",
  boxShadow: "0 8px 20px rgba(17, 24, 39, 0.12)",
  border: "1px solid rgba(124, 58, 237, 0.15)",
},

  levelRowLocked: {
    background: "#f3f4f6",
    boxShadow: "none",
  },
  levelDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    flexShrink: 0,
  },
  levelNameNew: {
    flex: 1,
    fontSize: "16px",
    fontWeight: "700",
    color: "#111827",
    textAlign: "left",
  },
  levelNameLocked: {
    color: "#9ca3af",
  },
  lockIconNew: {
    fontSize: "18px",
  },

  topBar: {
    display: "flex",
    justifyContent: "space-between",
    width: "300px",
    margin: "20px auto",
  },

  circle: {
    width: "50px",
    height: "50px",
    borderRadius: "50%",
    border: "4px solid #4CAF50",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "bold",
  },

  card: {
    margin: "20px auto",
    padding: "20px",
    border: "1px solid #ddd",
    borderRadius: "12px",
    width: "300px",
  },

  flag: {
    width: "200px",
    height: "120px",
    objectFit: "cover",
    borderRadius: "8px",
    marginBottom: "20px",
    border: "1px solid #ccc",
    background: "#e8e8e8",
    boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
  },

  options: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },

  optionBtn: {
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #ccc",
    cursor: "pointer",
    background: "#f9f9f9",
  },

  restartBtn: {
    padding: "10px 20px",
    background: "#4CAF50",
    color: "white",
    border: "none",
    borderRadius: "6px",
  },

  authContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    background: "#f4f6f8",
  },

  authCard: {
    width: "320px",
    padding: "30px 25px",
    borderRadius: "14px",
    background: "white",
    boxShadow: "0 10px 30px rgba(0,0,0,0.1)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  headerBlock: {
    marginBottom: "15px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },

  title: {
    fontSize: "22px",
    fontWeight: "600",
  },

  subtitle: {
    fontSize: "13px",
    color: "#666",
  },

  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #ddd",
  },

  primaryBtn: {
    width: "100%",
    padding: "10px",
    background: "#4CAF50",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
  },

  switchText: {
    marginTop: "10px",
    color: "#007bff",
    cursor: "pointer",
  },

  errorBox: {
    background: "#ffdddd",
    color: "#d8000c",
    padding: "8px",
    borderRadius: "6px",
  },

  dashboardContainer: {
    textAlign: "center",
    padding: "40px",
  },

  cardGrid: {
    display: "flex",
    justifyContent: "center",
    gap: "20px",
    marginTop: "30px",
    flexWrap: "wrap",
  },

  menuCard: {
    width: "180px",
    height: "120px",
    background: "white",
    boxShadow: "0 10px 25px rgba(0,0,0,0.1)",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "bold",
  },

  backBtn: {
    padding: "8px 15px",
    border: "none",
    borderRadius: "6px",
    background: "#333",
    color: "white",
    cursor: "pointer",
    marginBottom: "20px",
  },

  leaderboardContainer: {
    textAlign: "center",
    padding: "30px",
  },

  leaderboardCard: {
    width: "60%",
    margin: "10px auto",
    padding: "12px",
    borderRadius: "10px",
    border: "1px solid #ddd",
    background: "#fafafa",
    display: "flex",
    justifyContent: "space-between",
    transition: "0.2s",
    cursor: "pointer",
  },
  levelsContainer: {
    textAlign: "center",
    padding: "30px",
  },
  levelsGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    alignItems: "center",
    marginTop: "30px",
  },
  levelCard: {
    width: "250px",
    padding: "20px",
    borderRadius: "12px",
    border: "2px solid #ddd",
    background: "white",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    transition: "0.2s",
    position: "relative",
  },
  levelName: {
    fontSize: "18px",
    fontWeight: "bold",
    flex: 1,
  },
  lockIcon: {
    fontSize: "24px",
  },
};
